// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getUUIDByIndex.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirpIDFromIndex = `-- name: GetChirpIDFromIndex :one
SELECT id
FROM chirps
ORDER BY created_at
OFFSET $1
LIMIT 1
`

func (q *Queries) GetChirpIDFromIndex(ctx context.Context, offset int32) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getChirpIDFromIndex, offset)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserIDFromIndex = `-- name: GetUserIDFromIndex :one
SELECT id
FROM users
ORDER BY created_at
OFFSET $1
LIMIT 1
`

func (q *Queries) GetUserIDFromIndex(ctx context.Context, offset int32) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserIDFromIndex, offset)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
